dist: precise
sudo: false

language: java

cache:
  directories:
    - $HOME/.m2

jdk:
  - openjdk7
  - oraclejdk8

script:
  - mvn clean verify

jobs:
  include:
    - stage: integration-test
      jdk: oraclejdk8
      env: test=migration
      script: mvn clean verify -Dtest='com.ribose.jenkins.plugin.awscodecommittrigger.it.feature.migration.*'

    - stage: integration-test
      jdk: oraclejdk8
      env: test=pipeline
      script: mvn clean verify -Dtest='com.ribose.jenkins.plugin.awscodecommittrigger.it.feature.pipeline.*'

    - stage: integration-test
      jdk: oraclejdk8
      env: test=scmconfig
      script: mvn clean verify -Dtest='com.ribose.jenkins.plugin.awscodecommittrigger.it.feature.scmconfig.*'

    - stage: integration-test
      jdk: oraclejdk8
      env: test=subscribed_branch
      script: mvn clean verify -Dtest='com.ribose.jenkins.plugin.awscodecommittrigger.it.feature.subscribed_branch.*'

    - stage: integration-test
      jdk: oraclejdk8
      env: test=threads
      script: mvn clean verify -Dtest='com.ribose.jenkins.plugin.awscodecommittrigger.it.feature.threads.*'
