dist: precise
sudo: false

language: java

cache:
  directories:
    - $HOME/.m2

jdk:
  - openjdk7
  - oraclejdk8

script:
  - mvn clean verify

jobs:
  include:
    - stage: integration-test
      jdk: oraclejdk8
      script: mvn clean verify -Dtest='com.ribose.jenkins.plugin.awscodecommittrigger.it.feature.migration.*'

    - stage: integration-test
      jdk: oraclejdk8
      script: mvn clean verify -Dtest='com.ribose.jenkins.plugin.awscodecommittrigger.it.feature.pipeline.*'

    - stage: integration-test
      jdk: oraclejdk8
      script: mvn clean verify -Dtest='com.ribose.jenkins.plugin.awscodecommittrigger.it.feature.scmconfig.*'

    - stage: integration-test
      jdk: oraclejdk8
      script: mvn clean verify -Dtest='com.ribose.jenkins.plugin.awscodecommittrigger.it.feature.subscribed_branch.*'

    - stage: integration-test
      jdk: oraclejdk8
      script: mvn clean verify -Dtest='com.ribose.jenkins.plugin.awscodecommittrigger.it.feature.threads.*'
