dist: precise
sudo: required

cache:
  directories:
    - $HOME/.m2

language: java

script:
  - jdk_switcher use openjdk7
  - mvn clean verify

  - jdk_switcher use oraclejdk8
  - mvn clean verify -P$TRAVIS_BRANCH
